# Generated by Django 4.0.3 on 2022-08-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
