# Generated by Django 4.0.3 on 2022-08-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list_app',
            name='option_one',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_list_app',
            name='option_three',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo_list_app',
            name='option_two',
            field=models.BooleanField(default=False),
        ),
    ]
