# Generated by Django 4.0.3 on 2022-08-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0002_todo_list_app_option_one_todo_list_app_option_three_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_app',
            name='option_one',
            field=models.BooleanField(default=False, verbose_name='High'),
        ),
        migrations.AlterField(
            model_name='todo_list_app',
            name='option_three',
            field=models.BooleanField(default=False, verbose_name='Low'),
        ),
        migrations.AlterField(
            model_name='todo_list_app',
            name='option_two',
            field=models.BooleanField(default=False, verbose_name='Medium'),
        ),
    ]
