# Generated by Django 4.0.3 on 2022-08-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0003_alter_todo_list_app_option_one_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo_list_app',
            name='option_one',
        ),
        migrations.RemoveField(
            model_name='todo_list_app',
            name='option_three',
        ),
        migrations.RemoveField(
            model_name='todo_list_app',
            name='option_two',
        ),
        migrations.AddField(
            model_name='todo_list_app',
            name='roles',
            field=models.CharField(choices=[('high', 'HIGH'), ('medium', 'MEDIUM'), ('low', 'LOW')], default='user', max_length=10),
        ),
    ]
