# Generated by Django 4.0.3 on 2022-08-19 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0005_alter_todo_list_app_roles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo_list_app',
            name='roles',
            field=models.CharField(choices=[('HIGH🔴', 'HIGH'), ('MEDIUM🟡', 'MEDIUM'), ('LOW🔵', 'LOW')], default='user', max_length=10),
        ),
    ]
