# Generated by Django 4.0.3 on 2022-08-19 08:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list_app', '0007_alter_todo_list_app_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo_list_app',
            name='due_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='todo_list_app',
            name='roles',
            field=models.CharField(choices=[('HIGH', 'HIGH'), ('MEDIUM', 'MEDIUM'), ('LOW', 'LOW')], default='default', max_length=10),
        ),
    ]
